#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# self-deploy.sh  —  GCP self-deployment, made easy
#
# Usage:  ./scripts/self-deploy.sh <ENV>
#   ENV   environment name — must have a matching env/<ENV>.tfvars
#         (e.g. customer)
#
# What it does, in plain terms:
#   1. Enables the GCP APIs Terraform needs (under YOUR already-authenticated
#      gcloud identity — this script needs project-admin rights to run)
#   2. Creates a scoped deployer Service Account (not your own admin identity)
#      with just the roles Terraform needs, and a JSON key for it
#   3. Initializes the Terraform state bucket
#   4. Optionally runs the actual Terraform deploy — 2 applies (repo root,
#      then cicd/; down from the original 4 separate layers, but not all the
#      way to 1 — see cicd/main.tf's file header for why), after one clear
#      confirmation, since that step creates real cloud resources and costs
#      money
#
# cicd_provider = "none" (self-service, e.g. env/customer.tfvars) generates
# its own DB/Redis/Neo4j/ArgoCD credentials and the app's shared secret
# directly in Terraform — no master secret, no password prompts here.
#
# Requires: gcloud (authenticated with a project-admin identity), kubectl,
#           jq, curl, terraform.
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <ENV>"
  echo "  ENV  must have a matching env/<ENV>.tfvars (e.g. customer)"
  exit 1
fi
ENV="$1"
TFVARS="${REPO_ROOT}/env/${ENV}.tfvars"

if [[ ! -f "${TFVARS}" ]]; then
  echo "ERROR: ${TFVARS} not found."
  exit 1
fi

for bin in gcloud kubectl jq curl terraform; do
  command -v "$bin" >/dev/null 2>&1 || { echo "ERROR: '$bin' is required but not installed."; exit 1; }
done

echo "════════════════════════════════════════════════════════════════"
echo " Ekai GCP self-deploy — environment: ${ENV}"
echo "════════════════════════════════════════════════════════════════"
echo

PROJECT_ID=$(grep -E '^project_id\s*=' "${TFVARS}" | head -1 | sed 's/.*=\s*"\(.*\)".*/\1/')
[[ -z "${PROJECT_ID}" || "${PROJECT_ID}" == "REPLACE_ME" ]] && { echo "ERROR: set a real project_id in ${TFVARS} first."; exit 1; }
REGION=$(grep -E '^region\s*=' "${TFVARS}" | head -1 | sed 's/.*=\s*"\(.*\)".*/\1/')
[[ -z "${REGION}" ]] && { echo "ERROR: could not read 'region' from ${TFVARS}"; exit 1; }
CLUSTER_NAME=$(grep -E '^cluster_name\s*=' "${TFVARS}" | head -1 | sed 's/.*=\s*"\(.*\)".*/\1/')

echo "==> Project: ${PROJECT_ID}"
echo "==> Region:  ${REGION}"
echo "==> Currently authenticated as: $(gcloud config get-value account 2>/dev/null)"
echo "    (this identity needs project-admin rights to run this script —"
echo "     it is NOT the identity Terraform will use)"
echo

CICD_PROVIDER=$(grep -E '^cicd_provider\s*=' "${TFVARS}" | head -1 | sed 's/.*=\s*"\(.*\)".*/\1/')
[[ -z "${CICD_PROVIDER}" ]] && CICD_PROVIDER="none"
if [[ "${CICD_PROVIDER}" == "none" ]]; then
  echo "==> cicd_provider = \"none\" (self-service) — the cluster/platform"
  echo "    submodules generate DB/Redis/Neo4j/ArgoCD credentials directly, no master secret needed."
fi

OUT_DIR="${REPO_ROOT}/.self-deploy"
mkdir -p "${OUT_DIR}"
SECRETS_FILE="${OUT_DIR}/${ENV}-generated-secrets.txt"
: > "${SECRETS_FILE}"
chmod 600 "${SECRETS_FILE}"
echo "# Generated by self-deploy.sh for env=${ENV} — copy into your password manager, then delete this file" >> "${SECRETS_FILE}"

# ── Step 1 — Enable required GCP APIs ─────────────────────────────────────────
echo "──── Step 1/4: Enable GCP APIs ─────────────────────────────────────"
REQUIRED_APIS=(
  compute.googleapis.com
  container.googleapis.com
  sqladmin.googleapis.com
  dns.googleapis.com
  secretmanager.googleapis.com
  servicenetworking.googleapis.com
  artifactregistry.googleapis.com
  iam.googleapis.com
  iamcredentials.googleapis.com
  cloudresourcemanager.googleapis.com
)
echo "==> Enabling: ${REQUIRED_APIS[*]}"
gcloud services enable "${REQUIRED_APIS[@]}" --project="${PROJECT_ID}"
echo "✓ APIs enabled."
echo

# ── Step 2 — Deployer Service Account + roles ─────────────────────────────────
echo "──── Step 2/4: Deployer Service Account ────────────────────────────"
SA_NAME="ekai-terraform-${ENV}"
SA_EMAIL="${SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"

if gcloud iam service-accounts describe "${SA_EMAIL}" --project="${PROJECT_ID}" >/dev/null 2>&1; then
  echo "==> Service account ${SA_EMAIL} already exists — reusing."
else
  echo "==> Creating service account ${SA_EMAIL}..."
  gcloud iam service-accounts create "${SA_NAME}" \
    --project="${PROJECT_ID}" \
    --display-name="Ekai Terraform deployer (${ENV})"
fi

# Predefined roles cover almost everything a single-purpose deployer identity
# needs — no custom role JSON to author/maintain, unlike AWS (no equivalently
# complete predefined-policy catalog there). resourcemanager.projectIamAdmin
# is the broadest of these: needed so Terraform can grant project-level roles
# (logging.logWriter, secretmanager.secretAccessor, artifactregistry.reader,
# ...) to the GSAs it creates for GKE nodes / ESO / cert-manager / the shared
# app Workload Identity SA.
PROJECT_ROLES=(
  roles/compute.networkAdmin
  roles/servicenetworking.networksAdmin
  roles/container.admin
  roles/cloudsql.admin
  roles/dns.admin
  roles/secretmanager.admin
  roles/artifactregistry.admin
  roles/iam.serviceAccountAdmin
  roles/iam.serviceAccountUser
  roles/resourcemanager.projectIamAdmin
)
for ROLE in "${PROJECT_ROLES[@]}"; do
  gcloud projects add-iam-policy-binding "${PROJECT_ID}" \
    --member="serviceAccount:${SA_EMAIL}" \
    --role="${ROLE}" \
    --condition=None \
    --quiet >/dev/null
done
echo "✓ Project-level roles granted to ${SA_EMAIL}."

# Fresh key every run, same reasoning as AWS's script: a previously created
# key's secret is unrecoverable by the time this runs a second time (GCP
# never returns it again either), and this script always truncates
# SECRETS_FILE. Old keys are deleted outright (GCP has no "deactivate", and
# no 2-key limit like AWS to work around).
mapfile -t OLD_KEYS < <(gcloud iam service-accounts keys list \
  --iam-account="${SA_EMAIL}" --managed-by=user --format='value(name)')
for KEY in "${OLD_KEYS[@]}"; do
  echo "==> Deleting previous key ${KEY##*/}..."
  gcloud iam service-accounts keys delete "${KEY##*/}" --iam-account="${SA_EMAIL}" --quiet
done

KEY_FILE="${OUT_DIR}/${ENV}-deployer-key.json"
echo "==> Creating a fresh key for ${SA_EMAIL}..."
gcloud iam service-accounts keys create "${KEY_FILE}" --iam-account="${SA_EMAIL}"
chmod 600 "${KEY_FILE}"
echo "GOOGLE_APPLICATION_CREDENTIALS=${KEY_FILE}" >> "${SECRETS_FILE}"
echo "✓ Key created: ${KEY_FILE}"
echo
echo "NOTE: if your GCP organization enforces the"
echo "  iam.disableServiceAccountKeyCreation constraint, the command above"
echo "  fails — that org has opted out of downloadable SA keys entirely, and"
echo "  this script's auth approach won't work there (Workload Identity"
echo "  Federation would be needed instead, out of scope for this script)."
echo

# ── Step 3 — State backend ────────────────────────────────────────────────────
echo "──── Step 3/4: State backend ───────────────────────────────────────"
"${SCRIPT_DIR}/init-state-backend.sh" "${ENV}" "${PROJECT_ID}"

BUCKET_FROM_TFVARS=$(grep -E '^state_bucket_name\s*=' "${TFVARS}" | head -1 | sed 's/.*=\s*"\(.*\)".*/\1/')
BUCKET="${BUCKET_FROM_TFVARS:-ekai-terraform-state-${ENV}-${PROJECT_ID}}"
# storage.admin, not just objectAdmin -- self-deploy-destroy.sh's optional
# cleanup deletes the bucket itself (storage.buckets.delete), which
# objectAdmin doesn't grant (object-level permissions only).
echo "==> Granting ${SA_EMAIL} bucket admin on gs://${BUCKET}..."
gcloud storage buckets add-iam-policy-binding "gs://${BUCKET}" \
  --member="serviceAccount:${SA_EMAIL}" \
  --role="roles/storage.admin" \
  --quiet >/dev/null
echo "✓ State bucket access granted."
echo

if [[ "${CICD_PROVIDER}" == "none" ]]; then
  echo "==> cicd_provider = \"none\" (self-service) — no password prompts, no"
  echo "    master secret. The platform submodule generates its own ArgoCD admin"
  echo "    password, the cluster submodule its own Cloud SQL credentials. Retrieve"
  echo "    the ArgoCD password after apply from the app secret's ARGOCD_PASSWORD"
  echo "    key, or run (from examples/self-deploy/root):"
  echo "    terraform output -raw argocd_admin_password_plaintext"
  echo
fi

# ── Step 4 — Deploy (optional) ────────────────────────────────────────────────
echo "──── Step 4/4: Deploy infrastructure ───────────────────────────────"
echo "Everything above is prep — no cluster infrastructure has been created yet."
echo "This next step creates real GCP resources (VPC, GKE, Cloud SQL, ...) and costs money."
echo
read -rp "Run the Terraform deploy now (2 applies — bootstrap+cluster+platform, then cicd)? [y/N] " CONFIRM
if [[ ! "${CONFIRM}" =~ ^[Yy]$ ]]; then
  echo
  echo "Skipped. When you're ready, deploy locally:"
  echo "  export GOOGLE_APPLICATION_CREDENTIALS=${KEY_FILE}"
  echo "  cd ${REPO_ROOT}/examples/self-deploy/root"
  echo "  terraform init -backend-config=../../../env/backend-${ENV}.tfbackend"
  echo "  terraform apply -var-file=../../../env/${ENV}.tfvars"
  echo "  cd ../cicd"
  echo "  (needs 'kubectl port-forward svc/argocd-server -n argocd 8080:80' running first — see cicd/providers.tf's comments for why)"
  echo "  terraform init -backend-config=../../../env/backend-${ENV}-cicd.tfbackend"
  echo "  terraform apply -var-file=../../../env/${ENV}.tfvars"
  echo
  echo "Generated key/secrets saved at: ${SECRETS_FILE} / ${KEY_FILE}"
  echo "Copy them into your password manager, then delete these files."
  exit 0
fi

export GOOGLE_APPLICATION_CREDENTIALS="${KEY_FILE}"
echo "==> Activating deployer identity for gcloud/kubectl calls..."
gcloud auth activate-service-account "${SA_EMAIL}" --key-file="${KEY_FILE}"
gcloud config set project "${PROJECT_ID}" >/dev/null

echo "==> Waiting for the new key to propagate..."
for i in $(seq 1 20); do
  if gcloud projects describe "${PROJECT_ID}" >/dev/null 2>&1; then
    echo "✓ Key is active."
    break
  fi
  sleep 5
done

# 2 applies, in order: bootstrap+cluster+platform first (its state feeds
# cicd's terraform_remote_state read — see cicd/main.tf's file header for why
# cicd can't be folded into this same apply), then cicd. Both run from
# examples/self-deploy/{root,cicd} — the repo root and cicd/ directories are
# pure Terraform modules now (no backend block of their own; see
# providers.tf / cicd/providers.tf), so they can't be applied directly.
# examples/self-deploy/{root,cicd} are the actual state-holding root configs
# that wrap them — see examples/self-deploy/root/main.tf's header comment.
echo
echo "════════ terraform apply (bootstrap + cluster + platform) ════════"
cd "${REPO_ROOT}/examples/self-deploy/root"
terraform init -upgrade -reconfigure -backend-config="../../../env/backend-${ENV}.tfbackend"
terraform apply -auto-approve -compact-warnings -var-file="../../../env/${ENV}.tfvars"

# ── cicd — needs a port-forward to ArgoCD's Service (see cicd/providers.tf:
# server_addr = "localhost:8080"). Kept this way deliberately for self-deploy
# instead of the real ingress hostname AWS uses — a fresh client domain's
# wildcard cert depends on Cloud DNS being delegated at the registrar first
# (an out-of-band, human-timed step Terraform can't wait for), which would
# otherwise block ArgoCD auth before the cluster even has its first
# Application. Port-forwarding straight to the Service's ClusterIP sidesteps
# DNS delegation and cert issuance entirely for this step.
echo
echo "════════ terraform apply (cicd) ════════"
echo "==> Fetching cluster credentials for port-forward..."
gcloud container clusters get-credentials "${CLUSTER_NAME}" --region "${REGION}" --project "${PROJECT_ID}"

kubectl port-forward svc/argocd-server -n argocd 8080:80 >/dev/null 2>&1 &
PF_PID=$!
cleanup_pf() { kill "${PF_PID}" >/dev/null 2>&1 || true; }
trap cleanup_pf EXIT

echo "==> Waiting for ArgoCD port-forward to be ready..."
for i in $(seq 1 20); do
  if curl -sf http://localhost:8080/healthz >/dev/null 2>&1; then
    echo "✓ ArgoCD reachable on localhost:8080."
    break
  fi
  sleep 3
done

cd "${REPO_ROOT}/examples/self-deploy/cicd"
terraform init -upgrade -reconfigure -backend-config="../../../env/backend-${ENV}-cicd.tfbackend"
terraform apply -auto-approve -compact-warnings -var-file="../../../env/${ENV}.tfvars"

cleanup_pf
trap - EXIT

echo
echo "✓ Deploy complete for env=${ENV}."
echo "Generated key/secrets saved at: ${SECRETS_FILE} / ${KEY_FILE} — copy into your password manager, then delete these files."
